# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kpit/Desktop/TEST_KATAPULT/21_08/Ques_5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kpit/Desktop/TEST_KATAPULT/21_08/Ques_5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kpit/Desktop/TEST_KATAPULT/21_08/Ques_5/CMakeFiles /home/kpit/Desktop/TEST_KATAPULT/21_08/Ques_5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kpit/Desktop/TEST_KATAPULT/21_08/Ques_5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Engine

# Build rule for target.
Engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Engine
.PHONY : Engine

# fast build rule for target.
Engine/fast:
	$(MAKE) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/build
.PHONY : Engine/fast

#=============================================================================
# Target rules for targets named DataContainer

# Build rule for target.
DataContainer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DataContainer
.PHONY : DataContainer

# fast build rule for target.
DataContainer/fast:
	$(MAKE) -f CMakeFiles/DataContainer.dir/build.make CMakeFiles/DataContainer.dir/build
.PHONY : DataContainer/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named functionalities

# Build rule for target.
functionalities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 functionalities
.PHONY : functionalities

# fast build rule for target.
functionalities/fast:
	$(MAKE) -f CMakeFiles/functionalities.dir/build.make CMakeFiles/functionalities.dir/build
.PHONY : functionalities/fast

DataInitialized.o: DataInitialized.cpp.o

.PHONY : DataInitialized.o

# target to build an object file
DataInitialized.cpp.o:
	$(MAKE) -f CMakeFiles/DataContainer.dir/build.make CMakeFiles/DataContainer.dir/DataInitialized.cpp.o
.PHONY : DataInitialized.cpp.o

DataInitialized.i: DataInitialized.cpp.i

.PHONY : DataInitialized.i

# target to preprocess a source file
DataInitialized.cpp.i:
	$(MAKE) -f CMakeFiles/DataContainer.dir/build.make CMakeFiles/DataContainer.dir/DataInitialized.cpp.i
.PHONY : DataInitialized.cpp.i

DataInitialized.s: DataInitialized.cpp.s

.PHONY : DataInitialized.s

# target to generate assembly for a file
DataInitialized.cpp.s:
	$(MAKE) -f CMakeFiles/DataContainer.dir/build.make CMakeFiles/DataContainer.dir/DataInitialized.cpp.s
.PHONY : DataInitialized.cpp.s

Engine_Control_Unit.o: Engine_Control_Unit.cpp.o

.PHONY : Engine_Control_Unit.o

# target to build an object file
Engine_Control_Unit.cpp.o:
	$(MAKE) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/Engine_Control_Unit.cpp.o
.PHONY : Engine_Control_Unit.cpp.o

Engine_Control_Unit.i: Engine_Control_Unit.cpp.i

.PHONY : Engine_Control_Unit.i

# target to preprocess a source file
Engine_Control_Unit.cpp.i:
	$(MAKE) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/Engine_Control_Unit.cpp.i
.PHONY : Engine_Control_Unit.cpp.i

Engine_Control_Unit.s: Engine_Control_Unit.cpp.s

.PHONY : Engine_Control_Unit.s

# target to generate assembly for a file
Engine_Control_Unit.cpp.s:
	$(MAKE) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/Engine_Control_Unit.cpp.s
.PHONY : Engine_Control_Unit.cpp.s

Functionalities.o: Functionalities.cpp.o

.PHONY : Functionalities.o

# target to build an object file
Functionalities.cpp.o:
	$(MAKE) -f CMakeFiles/functionalities.dir/build.make CMakeFiles/functionalities.dir/Functionalities.cpp.o
.PHONY : Functionalities.cpp.o

Functionalities.i: Functionalities.cpp.i

.PHONY : Functionalities.i

# target to preprocess a source file
Functionalities.cpp.i:
	$(MAKE) -f CMakeFiles/functionalities.dir/build.make CMakeFiles/functionalities.dir/Functionalities.cpp.i
.PHONY : Functionalities.cpp.i

Functionalities.s: Functionalities.cpp.s

.PHONY : Functionalities.s

# target to generate assembly for a file
Functionalities.cpp.s:
	$(MAKE) -f CMakeFiles/functionalities.dir/build.make CMakeFiles/functionalities.dir/Functionalities.cpp.s
.PHONY : Functionalities.cpp.s

Test.o: Test.cpp.o

.PHONY : Test.o

# target to build an object file
Test.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Test.cpp.o
.PHONY : Test.cpp.o

Test.i: Test.cpp.i

.PHONY : Test.i

# target to preprocess a source file
Test.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Test.cpp.i
.PHONY : Test.cpp.i

Test.s: Test.cpp.s

.PHONY : Test.s

# target to generate assembly for a file
Test.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/Test.cpp.s
.PHONY : Test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... Engine"
	@echo "... DataContainer"
	@echo "... app"
	@echo "... functionalities"
	@echo "... DataInitialized.o"
	@echo "... DataInitialized.i"
	@echo "... DataInitialized.s"
	@echo "... Engine_Control_Unit.o"
	@echo "... Engine_Control_Unit.i"
	@echo "... Engine_Control_Unit.s"
	@echo "... Functionalities.o"
	@echo "... Functionalities.i"
	@echo "... Functionalities.s"
	@echo "... Test.o"
	@echo "... Test.i"
	@echo "... Test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

